FROM mcr.microsoft.com/mssql/server:2022-latest
USER root
RUN apt update && \
  apt install -y apt-transport-https software-properties-common && \
  wget -qO- https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc && \
  add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2022.list)" && \
  apt update && \
  apt install -y mssql-server-fts && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
