const privacyTable = {
  privacyTable: [
    {
      Section: "Youth Portal",
      "Data name": "First name",
      "Data category": "Registration data",
      "Data type": "Personalised",
      "Reason for collection": "User idenfification",
    },
    {
      Section: "Youth Portal",
      "Data name": "Last name",
      "Data category": "Registration data",
      "Data type": "Personalised",
      "Reason for collection": "User idenfification",
    },
    {
      Section: "Youth Portal",
      "Data name": "Gender",
      "Data category": "Registration data",
      "Data type": "Personalised",
      "Reason for collection": "User idenfification",
    },
    {
      Section: "Youth Portal",
      "Data name": "Email",
      "Data category": "Registration data",
      "Data type": "Personalised",
      "Reason for collection": "Login username",
    },
    {
      Section: "Youth Portal",
      "Data name": "Biography",
      "Data category": "Registration data",
      "Data type": "Personalised",
      "Reason for collection": "User information",
    },
    {
      Section: "Youth Portal",
      "Data name": "Country ID",
      "Data category": "Registration data",
      "Data type": "Personalised",
      "Reason for collection": "Matching to marketplace and opportunities",
    },
    {
      Section: "Youth Portal",
      "Data name": "Profile image",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Enrichment of user experience",
    },
    {
      Section: "Youth Portal",
      "Data name": "Qualification title",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Matching youth to relevant opportunities",
    },
    {
      Section: "Youth Portal",
      "Data name": "Qualification description",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Matching youth to relevant opportunities",
    },
    {
      Section: "Youth Portal",
      "Data name": "Qualification organization",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Verification of opportunity",
    },
    {
      Section: "Youth Portal",
      "Data name": "Qualification created",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Verification of opportunity",
    },
    {
      Section: "Youth Portal",
      "Data name": "Job title",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Matching youth to relevant opportunities",
    },
    {
      Section: "Youth Portal",
      "Data name": "Job description",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Matching youth to relevant opportunities",
    },
    {
      Section: "Youth Portal",
      "Data name": "Job organization",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Verification of opportunity",
    },
    {
      Section: "Youth Portal",
      "Data name": "Job created",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Verification of opportunity",
    },
    {
      Section: "Youth Portal",
      "Data name": "Skills",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "User information",
    },
    {
      Section: "Youth Portal",
      "Data name": "Completed opportunities",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Verification of completed opportunity",
    },
    {
      Section: "Youth Portal",
      "Data name": "Verified skills/credentials",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Verification of completed opportunity",
    },
    {
      Section: "Youth Portal",
      "Data name": "Time Zone",
      "Data category": "Registration data",
      "Data type": "Anonymised",
      "Reason for collection": "Log data for site analytics",
    },
    {
      Section: "Youth Portal",
      "Data name": "Device",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "User experience & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Mobile vs. Desktop",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "User experience & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Operating system",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "User experience & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Browser",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "User experience & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "New vs. Returning",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Usage measurement",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Log-Ins",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Location",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Times of access",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Search queries",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Funnel at Registration",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Bounce rate",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Origin/Referral",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Time spent",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Youth Portal",
      "Data name": "Certificate/Badges",
      "Data category": "Log data",
      "Data type": "Personalised",
      "Reason for collection": "Verification of completed opportunity",
    },
    {
      Section: "Youth Portal",
      "Data name": "Contact and Support Requests",
      "Data category": "Log data",
      "Data type": "Personalised",
      "Reason for collection": "Contact & Support",
    },
    {
      Section: "Partner Portal",
      "Data name": "First name of primary contact",
      "Data category": "Registration data",
      "Data type": "Personalised",
      "Reason for collection": "User idenfification",
    },
    {
      Section: "Partner Portal",
      "Data name": "Last name of primary contact",
      "Data category": "Registration data",
      "Data type": "Personalised",
      "Reason for collection": "User idenfification",
    },
    {
      Section: "Partner Portal",
      "Data name": "Email of primary contact",
      "Data category": "Registration data",
      "Data type": "Personalised",
      "Reason for collection": "Login username",
    },
    {
      Section: "Partner Portal",
      "Data name": "Cell phone of primary contact",
      "Data category": "Registration data",
      "Data type": "Personalised",
      "Reason for collection": "Login username",
    },
    {
      Section: "Partner Portal",
      "Data name": "Company name",
      "Data category": "Registration data",
      "Data type": "Anonymised",
      "Reason for collection": "Organisation identification",
    },
    {
      Section: "Partner Portal",
      "Data name": "Company URL",
      "Data category": "Registration data",
      "Data type": "Anonymised",
      "Reason for collection": "Organisation identification",
    },
    {
      Section: "Partner Portal",
      "Data name": "Company logo",
      "Data category": "Registration data",
      "Data type": "Anonymised",
      "Reason for collection": "Organisation identification",
    },
    {
      Section: "Partner Portal",
      "Data name": "Country ID",
      "Data category": "Registration data",
      "Data type": "Anonymised",
      "Reason for collection": "Matching to marketplace and opportunities",
    },
    {
      Section: "Partner Portal",
      "Data name": "Company tagline",
      "Data category": "Registration data",
      "Data type": "Anonymised",
      "Reason for collection": "Organisation identification",
    },
    {
      Section: "Partner Portal",
      "Data name": "Company description",
      "Data category": "Registration data",
      "Data type": "Anonymised",
      "Reason for collection": "Organisation identification",
    },
    {
      Section: "Partner Portal",
      "Data name": "Company registration docs",
      "Data category": "Registration data",
      "Data type": "Anonymised",
      "Reason for collection": "Organisation identification",
    },
    {
      Section: "Partner Portal",
      "Data name": "Opportunity title",
      "Data category": "Opportunity data",
      "Data type": "Anonymised",
      "Reason for collection": "Opportunity creation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Opportunity description",
      "Data category": "Opportunity data",
      "Data type": "Anonymised",
      "Reason for collection": "Opportunity creation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Opportunity region",
      "Data category": "Opportunity data",
      "Data type": "Anonymised",
      "Reason for collection": "Opportunity creation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Opportunity language",
      "Data category": "Opportunity data",
      "Data type": "Anonymised",
      "Reason for collection": "Opportunity creation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Opportunity dates",
      "Data category": "Opportunity data",
      "Data type": "Anonymised",
      "Reason for collection": "Opportunity creation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Opportunity participant limit",
      "Data category": "Opportunity data",
      "Data type": "Anonymised",
      "Reason for collection": "Opportunity creation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Opportunity skills / credentials",
      "Data category": "Opportunity data",
      "Data type": "Anonymised",
      "Reason for collection": "Opportunity creation",
    },
    {
      Section: "Partner Portal",
      "Data name": "ZLTO rewarded",
      "Data category": "Opportunity data",
      "Data type": "Anonymised",
      "Reason for collection": "Opportunity creation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Opportunity partner representatives name and surname",
      "Data category": "User profile data",
      "Data type": "Personalised",
      "Reason for collection": "Credentials management",
    },
    {
      Section: "Partner Portal",
      "Data name": "Credentials verified",
      "Data category": "Opportunity data",
      "Data type": "Personalised",
      "Reason for collection": "Credentials management",
    },
    {
      Section: "Partner Portal",
      "Data name": "Time Zone",
      "Data category": "Registration data",
      "Data type": "Anonymised",
      "Reason for collection": "Log data for site analytics",
    },
    {
      Section: "Partner Portal",
      "Data name": "Device",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "User experience & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Mobile vs. Desktop",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "User experience & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Operating system",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "User experience & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Browser",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "User experience & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "New vs. Returning",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Usage measurement",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Log-Ins",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Location",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Times of access",
      "Data category": "Log Data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Search queries",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Funnel at Registration",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Bounce rate",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Origin/Referral",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
    {
      Section: "Partner Portal",
      "Data name": "Time spent",
      "Data category": "Log data",
      "Data type": "Anonymised",
      "Reason for collection": "Platform insights & Marketplace optimisation",
    },
  ],
};

export default privacyTable;
