import React from "react";
import privacyTable from "./privacy-table-data";

const PrivacySection = () => {
  return (
    <div className="flex flex-col gap-6 overflow-hidden">
      <h1 className="mb-4 text-3xl font-bold">Privacy policy</h1>
      <div className="flex flex-col gap-4">
        <p className="text-gray-dark">
          <strong className="text-black">
            Yoma (Youth Agency Marketplace)s
          </strong>{" "}
          is a digital platform where youth can develop their skills, find
          opportunities, and achieve impact - while connecting to peers in a
          supportive community. Our mission is to positively impact youth, local
          communities, and the world! We are developing a digitally enabled
          ecosystem that is youth centric, provides value to all players and
          links up talent with opportunities and professional/entrepreneurial
          pathways.
        </p>
        <p className="text-gray-dark">
          We use the information we collect to provide you with a better
          learning-to-earning experience and fulfill our mission of providing
          free, accessible skills development, impact, and employment
          opportunities to youth worldwide. RLabs is a non-profit organization,
          so that a commercial for-profit motive will not interfere with our
          mission of providing a trusted ecosystem for youth.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">
          Our Privacy Policy is based on the commitment to the following Privacy
          Principles:
        </p>
        <p className="text-gray-dark">
          <span className="font-semibold text-black">
            1. Self-Sovereign Identity (SSI).{" "}
          </span>
          This means that all the users on Yoma are in complete control and
          ownership of their data. They decide what data they want to share and
          with whom.
        </p>
        <p className="text-gray-dark">
          <span className="font-semibold text-black">
            2. Data portability.{" "}
          </span>
          As part of being SSI-focused, our users are able to use the data from
          Yoma on other platforms, even offline, for example, personal
          identification. The data that is gathered and generated by Yoma has
          value beyond the platform itself.
        </p>
        <p className="text-gray-dark">
          <span className="font-semibold text-black">
            3. Data minimization.{" "}
          </span>
          We understand how valuable our users&apos; data is to them, and for
          that reason, we only collect data that we need in order for our users
          to benefit from the services offered by Yoma.
        </p>
        <p className="text-gray-dark">
          In order for us to continue discussing the Privacy Policy, we need to
          understand some key terms used in the document.
        </p>
        <p className="text-gray-dark">
          <span className="font-semibold text-black">a) Platform – </span>This
          refers to everything that Yoma offers online. It encompasses various
          devices and services, listed below.
        </p>
        <p className="text-gray-dark">
          <span className="font-semibold text-black">b) Website – </span>This is
          the Yoma website that is accessed through a browser on either a
          computer or mobile device.
        </p>
        <p className="text-gray-dark">
          <span className="font-semibold text-black">c) Desktop – </span>This
          refers specifically to the website accessed only via computer or
          laptop.
        </p>
        <p className="text-gray-dark">
          <span className="font-semibold text-black">d) Services – </span>The
          services refer to the backend development and data handling procedures
          that have been built in order to offer the experience that users
          receive. The backend development and data handling define the scope of
          the tools that the platform offers our users. For example, one of our
          services is the ability for a youth to take part in an opportunity or
          challenge with an opportunity partner. Another example might be the
          ability for opportunity partners to be able to verify and reward youth
          for successfully completing a challenge. The services offered by Yoma
          have been designed in such a way that we only require a small about of
          personal data in order for us to offer our services (data
          minimization.)
        </p>
        <p className="text-gray-dark">
          <span className="font-semibold text-black">e) Partners – </span>We
          have a number of different partners that provide value to youth on the
          platform. Below are the types of partners involved currently.
        </p>
        <p className="ml-3 text-gray-dark">
          - Opportunity partners (OP). These are independent opportunity
          providers who list their opportunities on Yoma for youth to
          participate in. They are responsible for hosting, managing, reviewing
          and rewarding youth for completing opportunities.
        </p>
        <p className="mb-0 ml-4 text-gray-dark">
          &#9702; Our current list of opportunity partners on the platform
          comprises of:
        </p>
        <p className="-mb-2 ml-5 text-gray-dark">
          <span className="font-semibold text-black">&#8226; Atingi</span>
        </p>
        <p className="-mb-2 ml-5 text-gray-dark">
          <span className="font-semibold text-black">&#8226; Rlabs</span>
        </p>
        <p className="-mb-2 ml-5 text-gray-dark">
          <span className="font-semibold text-black">&#8226; Umuzi</span>
        </p>
        <p className="-mb-2 ml-5 text-gray-dark">
          <span className="font-semibold text-black">
            &#8226; Africa Coding Network
          </span>
        </p>
        <p className="ml-5 text-gray-dark">
          <span className="font-semibold text-black">&#8226; Goodwall</span>
        </p>
        <p className="mb-2 text-lg font-semibold text-black">Introduction</p>
        <p className="text-gray-dark">
          This is the main privacy policy for Yoma, and it applies to all our
          Platforms.
        </p>
        <p className="text-gray-dark">
          Yoma (&quot;We&quot;) respect your privacy and are determined to
          protect your personal data to create a safe and secure environment for
          all users.
        </p>
        <p className="text-gray-dark">
          Note: For each section in this Privacy Policy, you can view all
          general privacy practices at the beginning of the section and see more
          information by reviewing &quot;Learn More&quot; for the relevant
          section.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">Purpose</p>
        <p className="text-gray-dark">
          This privacy notice explains you how we protect your privacy and how
          we collect and process your personal data through your use of this
          platform (regardless of where you visit it from). We&apos;ll also tell
          you about your privacy rights and how the data protection law protects
          you.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">Data Controller</p>
        <p className="text-gray-dark">
          RLabs is the controller and responsible for your personal data
          (collectively referred to as &quot;we&quot;, &quot;us&quot; or
          &quot;our&quot; in this privacy policy). Our contact details of the
          person responsible for our personal data compliance is Desme Jacobs,
          admin@yoma.world. RLabs is the controller and responsible for this
          website. Physical and postal address 54 Kiewiet Road, Bridgetown,
          Athlone 7764 Cape Town, Western Cape, South Africa
        </p>
        <p className="mb-2 text-lg font-semibold text-black">
          Third-party links
        </p>
        <p className="text-gray-dark">
          This website may include links to third-party websites, plug-ins and
          applications. Clicking on those links or enabling those connections
          may allow third parties to collect or share data about you. We do not
          control these third-party websites and are not responsible for their
          privacy statements. When you leave our website, we encourage you to
          read the privacy notice of every website you visit. The plug-ins that
          are used on Yoma do however delete all your data once you close the
          session, so there is no risk of your data being stored anywhere after
          you&apos;ve left the site.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">
          The Information we collect
        </p>
        <p className="mb-2 ml-3 font-semibold text-black">
          a) Personal Data in the User Profile
        </p>
        <p className="ml-4 text-gray-dark">
          When you register on Yoma, you can choose a password and provide first
          name, last name, country of residence and a valid email address. We
          require your full name, e-mail address and password to successfully
          create an account and provide login credentials. After registration,
          users can access and revise their profile at any time and edit or
          update the data provided during the registration. Users can only
          access their own profile. The personal data provided cannot be viewed
          by other users. Registered users can also use a profile picture for
          their profile, which is visible to other users. The e-mail address is
          also used to send the user information on specific opportunities
          provided by Yoma or partner institutions, provided that these offers
          are compatible with the goal of providing learning to earning
          opportunities. Users have the possibility to object to this use at any
          time. In order to enable the user to make the best possible use of the
          platform offerings and to fulfil the purpose of Yoma, the e-mail
          address is also used to send the user information on specific
          opportunities provided by Yoma or partner institutions, provided that
          these offers are compatible with the goal of providing learning to
          earning opportunities. Users have the possibility to object to this
          use at any time.
        </p>
        <p className="ml-4 text-gray-dark">
          Retention period: 12 months, or until the user requests that their
          data be deleted from the platform.
        </p>
        <p className="mb-2 ml-3 font-semibold text-black">
          b) Other Personal Data
        </p>
        <p className="ml-4 text-gray-dark">
          When you use the Yoma website and services, we may collect other
          information about your activities on the Website, including challenges
          or competitions you have participated in and content you have
          submitted as part of those activities, or content you post in public
          or private portions of the site. All actions undertaken while using
          the platform will be stored in a way that allows tracing back which
          account undertook certain actions.This includes any information that
          you provide to us directly, whether through our platforms, personal
          interaction or via phone, SMSs or any other medium.
        </p>
        <p className="ml-4 text-gray-dark">
          Retention period: 12 months, or until the user requests that their
          data be deleted from the platform.
        </p>
        <p className="mb-2 ml-3 font-semibold text-black">
          c) Technical and Log Data
        </p>
        <p className="ml-4 text-gray-dark">
          When you access and use Yoma, log data will be stored. We collect or
          retrieve your information using technologies such as cookies, web
          beacons (explained below) and other technologies. Depending on how you
          access and use our platforms, this may include information about your
          interactions with our platforms, browser or device information (for
          example the type of device you&apos;re using, how you access our
          platforms, your browser or operating system, and your Internet
          Protocol (&quot;IP&quot;) address). Please see our cookie policy for
          further details. The log data will be analysed in an anonymised form.
          Log data for the last 12 months is visible to the administrators.
          Additionally, administrators do have access to the database to trace
          back which user contributed certain posts or undertook certain actions
          in case of improper use or use of abusive language. Other participants
          do not have access to the data. Thus, this data cannot be seen by the
          other participants or partners.
        </p>
        <p className="ml-4 text-gray-dark">
          Retention period: 12 months, or until the user requests that their
          data be deleted from the platform.
        </p>
        <p className="mb-0 ml-5 font-semibold text-black">Cookies:</p>
        <span className="mb-2 ml-5 text-gray-dark">
          &#8226; Websites collect information on their visitors using
          &quot;cookies&quot;. Cookies are text files assisting websites to
          identify visitors by allotting a unique identifying code to each
          device. This is done to optimize content preferences and traffic
          patterns and offer personalized experience. Cookies are sometimes also
          used to &quot;link&quot; your device to data hosted in an alternate
          place. Please note that some features of the Website may not work as
          intended if you disable cookies. For more information about the
          cookies we use, please see our Cookie Policy.
        </span>
        <p className="mb-0 ml-5 font-semibold text-black">Web beacons:</p>
        <span className="mb-2 ml-5 text-gray-dark">
          &#8226; A web beacon is a technique used on web pages to be able to
          check that a user has accessed some content. Web beacons are typically
          used by third parties to monitor the activity of users at a website
          for the purpose of web analytics or page tagging.
        </span>
        <p className="mb-2 text-lg font-semibold text-black">
          The Information we do not collect
        </p>
        <p className="text-gray-dark">
          We do not collect any Special Categories of Personal Data about you
          (this includes details about your race or ethnicity, religious or
          philosophical beliefs, sex life, sexual orientation, political
          opinions, trade union membership, information about your health and
          genetic and biometric data). Nor do we collect any information about
          criminal convictions and offenses.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">
          If you choose not to provide your personal data
        </p>
        <p className="text-gray-dark">
          Where we need to collect your personal data, or under the terms of
          this privacy notice, and you fail to provide that data when requested,
          we may not be able to offer you the experience/service you expect.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">
          How we collect Information
        </p>
        <p className="mb-0 ml-3 text-gray-dark">
          <span className="font-semibold text-black">
            1. We collect information directly from you.{" "}
          </span>
          This includes personal data you provide when you:
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Register and create an account on our website
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Update your profile or post in public areas
        </p>
        <p className="ml-4 text-gray-dark">
          &#8226; Participate in specific features or offerings
        </p>
        <p className="mb-0 ml-3 text-gray-dark">
          <span className="font-semibold text-black">
            2. We may collect information from others, such as Yoma
          </span>
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Register on Yoma via one of the opportunity partners
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Choose to participate in a challenge from an opportunity
          partner
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Ask for verification of a completed learning opportunity
        </p>
        <p className="ml-4 text-gray-dark">&#8226; Want to redeem Zltos</p>
        <p className="mb-0 ml-3 text-gray-dark">
          <span className="font-semibold text-black">
            3. We collect some information automatically, such as technical data
            about the devices and activities you undertake on the platform.{" "}
          </span>
          Data<p className="ml-3 text-gray-dark">is collected when you:</p>
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Log in to the platform
        </p>
        <p className="ml-4 text-gray-dark">
          &#8226; Interact with our website and offerings
        </p>
        <p className="mb-2 text-lg font-semibold text-black">
          Why we use the Information
        </p>
        <p className="text-gray-dark">
          We use the information collected for the following purposes:
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Providing access to the platform and to the related services
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Customising the platform and your user experience
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Communicating with you regarding your account (e.g., if we may
          want to notify you about changes to our platforms or provide you with
          information about services)
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Informing you about specific opportunities and/or offers on
          the platform that may be of interest for you (based on your consent).
        </p>
        <p className="mb-4 ml-4 text-gray-dark">
          &#8226; Analysing and improving our services based on aggregated
          information
        </p>

        <div className="items mb-3 flex flex-col justify-center">
          <table className="border-collapse border text-[.5rem] md:text-base">
            <tbody>
              <tr>
                <th className="border p-px text-left md:p-2">Section</th>
                <th className="border p-px text-left md:p-2">Data name</th>
                <th className="border p-px text-left md:p-2">Data category</th>
                <th className="border p-px text-left md:p-2">Data type</th>
                <th className="border p-px text-left md:p-2">
                  Reason for collection
                </th>
              </tr>
              {privacyTable ? (
                privacyTable.privacyTable.map((item, index) => {
                  return (
                    <tr key={index}>
                      <td className="border p-px text-left text-gray-dark md:p-2">
                        {/* eslint-disable-next-line @typescript-eslint/dot-notation */}
                        {item["Section"]}
                      </td>
                      <td className="border p-px text-left text-gray-dark md:p-2">
                        {item["Data name"]}
                      </td>
                      <td className="border p-px text-left text-gray-dark md:p-2">
                        {item["Data category"]}
                      </td>
                      <td className="border p-px text-left text-gray-dark md:p-2">
                        {item["Data type"]}
                      </td>
                      <td className="border p-px text-left text-gray-dark md:p-2">
                        {item["Reason for collection"]}
                      </td>
                    </tr>
                  );
                })
              ) : (
                <></>
              )}
            </tbody>
          </table>
        </div>

        <p className="mb-2 text-lg font-semibold text-black">
          Comment on the purpose
        </p>
        <p className="mb-2 text-gray-dark">
          We will only use your personal data for the purposes for which we
          collected it, unless we reasonably consider that we need to use it for
          another reason and that reason is compatible with the original
          purpose.
        </p>
        <p className="mb-2 text-gray-dark">
          If we need to use your personal data for an unrelated purpose, we will
          notify you and we will explain the purpose and legal basis which
          allows us to do so.
        </p>
        <p className="text-gray-dark">
          Please note that we may process your personal data without your
          knowledge or consent, in compliance with the above rules, where this
          is required or permitted by law.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">
          Transparency: Roles and Permission
        </p>
        <p className="mb-2 font-semibold text-black">Yoma Youth</p>
        <p className="text-gray-dark">
          Yoma youth are the holders of their own data and are permitted to
          engage across opportunities, challenges and impact tasks, as well as
          apply for jobs found on Yoma. The Yoma Youth are able to build their
          own digital CV, and share their CV with employers on the platform, in
          accordance with self-determination. They are also able to earn and
          spend digital currency on the marketplace.
        </p>
        <p className="mb-2 font-semibold text-black">
          Opportunity Provider (OP)
        </p>
        <p className="text-gray-dark">
          OPs provide challenges, courses, and tasks for Yoma Youth to engage
          with. They are also responsible for issuing verified credentials to
          the Yoma Youth on successful completion of the challenge, course, or
          task. OPs are not able to initiate contact with Yoma Youth, however
          once a Yoma Youth has applied to take part in a challenge, course or
          impact opportunity, the OP is able to connect with them on their own
          website/platform. OPs do not have access to any youth data unless the
          youth actively initiate a connection with the OP in the form of taking
          part in a challenge. At this point, the OP will be able to view the
          youth member&apos;s name, surname, and email address.
        </p>
        <p className="mb-2 font-semibold text-black">
          Employment Provider (EP)
        </p>
        <p className="text-gray-dark">
          Much like OPs, EPs are not able to initiate a connection with Yoma
          Youth. Rather, the EP lists an employment opportunity for Yoma Youth
          to browse, and only once the Yoma Youth has shown interest and would
          like to form a connection to share their CV, is the EP able to
          communicate with the Yoma Youth. Like the OPs, once the connection is
          formed between the EP and Yoma Youth, the relationship will be managed
          off the Yoma portal, and between the Yoma Youth and EP. EPs do not
          have access to any youth data unless the youth actively initiate a
          connection with the EP in the form of showing interest in a possible
          job opportunity. At this point, the EP will be able to view the youth
          member&apos;s name, surname, and email address. The youth will be able
          to share their digital CV, as per above, with the EP. Any information
          shared between these two parties beyond the Yoma platform is beyond
          our control.
        </p>
        <p className="mb-2 font-semibold text-black">Yoma Technical Team</p>
        <p className="mb-2 text-gray-dark">
          This is the design and development team responsible with building and
          maintaining the platform. Only members of this team have access to the
          various databases and user information that is not encrypted. Access
          to the database is done strictly under the request 10 of the Product
          Owner and is limited to the fields specifically needed. This is often
          done when there is a user that is unable to access certain elements or
          features of Yoma, and the technical team is required to troubleshoot
          against a specific username and criteria. The technical team has
          access to all database information including, user email addresses for
          youth, OPs and EPs as well as name, country of origin and contact
          details. The technical team has been instructed to not look into the
          database unless expressly told to do so by the Product Manager or CTO.
          This is usually only done when there is a bug or query whereby the
          technical team needs specific details in order to help the user or
          diagnose a problem.
        </p>
        <p className="mb-1 ml-3 text-gray-dark">
          &#8226; We are committed to protect your personal information. We
          don&apos;t share your personal information with or give access to
          third parties unless you provide explicit consent to do so. Before any
          information is shared, we will ask for your consent and let you know
          what information is needed, why it is needed and with whom we are
          planning to share it. You may decide whether or not you want us to
          share your information. Circumstances in which we may share personal
          information with third parties:
        </p>
        <p className="ml-3 text-gray-dark">
          &#8226; We may share information with ecosystem partners or
          third-party providers.
        </p>
        <p className="mb-2 text-gray-dark">
          We may share information with ecosystem partners or third-party
          providers. Ecosystem partners are partners on the platform such as OPs
          and EPs who are actively engaged in connecting with the youth and
          other OPs/EPs on the platform. Third parties are service providers who
          offer a service to Yoma as a means to improve or optimise the service
          offering, for example, a third-party chat bot to help deal with user
          queries.
        </p>
        <p className="mb-2 text-gray-dark">
          Let&apos;s take a closer look at how, when, and why we may share data
          with these two parties.
        </p>
        <p className="text-gray-dark">
          &#8226; Our partners in the Yoma ecosystem consist of a number of
          different organizations that all collect customer information, this
          may include access to: Personal Information and Usage Information, to
          facilitate their services. We restrict the user&apos;s Personal
          Information that we share with them to the minimum data required by
          them for them to be able to offer their specific services. We require
          our Partners to maintain privacy and security of this data and limit
          their usage of the data provided to the extent applicable for
          executing their services. Specifically, the only data we share with
          our opportunity partners is your name and country when you want to
          participate in a challenge. When it comes to our employer partners, we
          give you the ability to share specific parts of your CV when you apply
          for a job. For example, you can choose not to share your previous work
          experience with employer partners if you don&apos;t want to. We also
          share your email address with them so that if they are interested in
          taking the conversation further, they are able to contact you
          directly.
        </p>
        <p className="text-gray-dark">
          &#8226; Third parties where you provide consent. In some cases, third
          parties may wish to obtain information about you in order to promote
          their products to you, or for whatever other reason. We may share
          information with third parties where you provide consent in the form
          of explicit opt-in. Such circumstances may include (but are not
          limited to) an entry into a competition sponsored by a third party
          where the provision of your information is a condition for entry to
          the competition, or where you express your interest in a product or
          service for which you would like more information. We will also ensure
          that your opt-in is explicit and that we provide a clear description
          of what data would be shared with the third party. Remember that once
          you have opted in to allow us to send your information to the third
          party, we cannot control what they do with your data; therefore, be
          sure to investigate their privacy policies before providing permission
          for us to share your information.
        </p>
        <p className="text-gray-dark">
          We also may share your personal data with Analytics providers [such as
          Google, based outside the EU]; search information providers [such as
          Google or Bing, based inside OR outside the EU] and/or Social Media
          sites [such as Facebook, Twitter, LinkedIn, based inside OR outside
          the EU]. All user data is assigned to a personal decentralized
          identifier (DID). These DIDs are held by the user and are paired with
          other DIDs through asymmetric key pairs which are cryptographically
          stored, and are used to create connections, sign contracts, issue
          credentials and issue rewards.
        </p>
        <p className="text-gray-dark">
          We may have to share your personal data with the parties set out below
          for the purposes set out in the table above.
        </p>
        <p className="-mb-2 ml-3 text-gray-dark">
          &#8226; External Third Parties Service
        </p>
        <p className="-mb-2 ml-3 text-gray-dark">
          &#8226; Providers based in the UK who provide IT and system
          administration services
        </p>
        <p className="-mb-2 ml-3 text-gray-dark">
          &#8226; Professional advisers including lawyers, bankers, auditors and
          insurers based in the UK who provide consultancy, banking, legal,
          insurance and accounting services.
        </p>
        <p className="-mb-2 ml-3 text-gray-dark">
          &#8226; Carefully selected external consultants who support Yoma in
          delivering their service to members.
        </p>
        <p className="ml-3 text-gray-dark">
          &#8226; Third parties to whom we may choose to sell, transfer, or
          merge parts of our business or our assets. Alternatively, we may seek
          to acquire other businesses or merge with them. If a change happens to
          our business, then the new owners may use your personal data in the
          same way as set out in this privacy notice.
        </p>
        <p className="mb-2 text-gray-dark">
          We require all third parties to respect the security of your personal
          data and to treat it in accordance with the law. We do not allow our
          third-party service providers to use your personal data for their own
          purposes and only permit them to process your personal data for
          specified purposes and in accordance with our instructions.
        </p>
        <p className="mb-2 font-semibold text-black">
          Links to Third-Party Websites:
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; There are different types of learning, earning and impact
          opportunities provided on Yoma. These opportunities are generally
          provided by partners of Yoma. To access an opportunity, our platform
          may provide links to third-party websites.
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; An additional registration on the partner&apos;s platform may
          be required. Do note that other websites may have varying Terms of
          Service, Privacy Policies and Copyright Policies. We advise our
          customers to read the policies governing third-party websites and note
          the Personal Information collected by them, before using the website.
        </p>
        <p className="ml-4 text-gray-dark">
          &#8226; Our Privacy Policy applies only to content, use, data
          collection and privacy relating to our website and platforms.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">Data Security</p>
        <p className="text-gray-dark">
          We have put in place appropriate security measures to prevent your
          personal data from being accidentally lost, used or accessed in an
          unauthorised way, altered or disclosed. In addition, we limit access
          to your personal data to those employees, agents, contractors and
          other third parties who have a business need to know. They will only
          process your personal data on our instructions and they are subject to
          a duty of confidentiality.
        </p>
        <p className="mb-0 text-gray-dark">
          We have put in place procedures to deal with any suspected personal
          data breach and will notify you and any applicable regulator of a
          breach where we are legally required to do so.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">
          Your Legal Rights
        </p>
        <p className="text-gray-dark">
          Unless subject to an exemption under the data protection laws, you
          have the following rights with respect to your personal data:
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Be informed that your personal information is being collected
          – at the point of collection – and the purposes for which it is being
          processed, retention periods and who it will be shared with;
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Access personal data held and processed by us;
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Rectification of any personal data that is inaccurate or
          incomplete;
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Erasure, or right to &quot;be forgotten&quot; if you would
          like to remove yourself and your data from the platform. This is
          initiated and executed by the youth/user;
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Erasure, or right to &quot;be forgotten&quot; if your data is
          no longer necessary for the purpose for which it was collected and
          Consent is the lawful basis for processing;
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Request that processing is restricted although we may still
          store their personal data; this is an alternative to requesting
          erasure of your data and the restriction is likely to be for a fixed
          period;
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Data portability if data is processed by automated means,
          which means to receive your data, or some of your data, in a format
          that can be easily used by another person (including the data subject
          themselves) or organisation;
        </p>
        <p className="-mb-2 ml-4 text-gray-dark">
          &#8226; Object to processing in certain circumstances, including
          preventing the use of their data for direct marketing;
        </p>
        <p className="ml-4 text-gray-dark">
          &#8226; Request human intervention if automated decision-making or
          profiling is used.
        </p>
        <p className="text-gray-dark">
          If you wish to exercise any of the rights set out above, please
          contact admin@yoma.world.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">
          What we may need from you
        </p>
        <p className="text-gray-dark">
          We may need to request specific information from you to help us
          confirm your identity and ensure your right to access your personal
          data (or to exercise any of your other rights). This is a security
          measure to ensure that personal data is not disclosed to any person
          who has no right to receive it. We may also contact you to ask you for
          further information in relation to your request to speed up our
          response.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">
          Time limit to respond
        </p>
        <p className="text-gray-dark">
          We try to respond to all legitimate requests within one month.
          Occasionally it may take us longer than a month if your request is
          particularly complex or you have made a number of requests, but should
          not exceed more than two months. In this case, we will notify you and
          keep you updated.
        </p>
        <p className="mb-2 text-lg font-semibold text-black">
          Changes to this Notice and your Duty to Inform us of Changes
        </p>
        <p className="text-gray-dark">
          This Privacy Notice is reviewed periodically in line with our policy
          review schedule.
        </p>
        <p className="mb-2 text-gray-dark">
          Please keep us informed if your personal data changes during your
          relationship with us. It is important that the personal data we hold
          about you is accurate and current.
        </p>
        <p className="mb-0 text-gray-dark">
          If this does not resolve your complaint to your satisfaction, you have
          the right to lodge a complaint with the Information
          Commissioner&apos;s Office. You can contact them as follows:
        </p>
        <p className="-mb-4 text-gray-dark">Commissioner</p>
        <p className="-mb-4 text-gray-dark">
          Wycliffe House, Water Lane, Wilmslow, Cheshire, SK9 5AF, England, UK
        </p>
        <p className="-mb-4 text-gray-dark">Tel.: +44 3031231113,</p>
        <p className="-mb-4 text-gray-dark">
          E-Mail: dataprotectionfee@ico.org.uk or by using the following Link
        </p>
        <p className="text-gray-dark">
          Contact formular: https://ico.org.uk/global/contact-us/email/
        </p>
        <p className="text-gray-dark">
          All data is currently stored in the UK in accordance with EU- and
          UK-GDPR regulations and standards.
        </p>
      </div>
    </div>
  );
};

export default PrivacySection;
